version: 2.1

# Use orb
orbs:
  no-self-approval: cci-labs/no-self-approval@1.0.1

            

jobs:
  build-and-test:
    docker:
      - image: cimg/base:2023.07
    steps:
      - run:
          name: Run build and tests
          command: echo "Running build and tests!"
  verify:
    docker:
      - image: cimg/base:2023.07
    steps:
      - no-self-approval/validate_approval
  deploy:
    docker:
      - image: cimg/base:2023.07
    steps:
      - run:
          name: Run tests
          command: echo "Running deployment!"


workflows:
  use-my-orb:
    jobs:
      - build-and-test
      - wait-for-approval:
          type: approval
          requires:
            - build-and-test
      - verify:
          requires:
            - wait-for-approval
      - deploy:
          requires:
            - verify